# Lecture 02: Data Types, Strings, Lists, and Arrays

---


* [Data Types](#Data-Types)
* [Numbers](#Numbers)
* [Strings](#Strings)
* [Boolean Values](#Boolean-Values)
* [Type Casting](#Type-Casting)
* [No Value](#No-Value)
* [Attributes and Methods](#Attributes-and-Methods)

---

## Set Up the Notebook

In [11]:
from datascience import *
import numpy as np

---

## Data Types

---

### `type`

### Data types
- Every value in Python has a **type**.
    - Use the `type` function to check a value's type.

---

### Demo: Types

Use the `type` function to check an objects type.

In [48]:
type(3)

int

In [49]:
x = 3
type(x) # The type of x is an int, not a name

int

In [2]:
3.2 + 2.5

5.7

In [50]:
type(x + 2.5)

float

In [51]:
type(3 / 1)

float

In [52]:
type(True)

bool

In [53]:
abs(-5)

5

In [54]:
type(abs)

builtin_function_or_method

---

## Numbers

---

### `ints` and `floats`

* Python has two real number types 
    * `int`: an integer of any size
    * `float`: a number with an optional fractional part
* An `int` never has a decimal point; a `float` always does
* A `float` might be printed using scientific notation
* Three limitations of `float` values:
    * They have limited size (but the limit is huge)
    * They have limited precision of 15-16 decimal places
    * After arithmetic, the final few decimal places can be wrong

---

### Demo: Numbers

Demonstrate integers and floats.

### ```int```
- If you add (`+`), subtract (`-`), multiply (`*`), or exponentiate (`**`) `int`s, the result will be another `int`.

In [ ]:
2

In [57]:
1 + 4

5

### ```float```
* A `float` is specified using a **decimal** point.
* A `float` might be printed using scientific notation.

In [58]:
# float
1.3

1.3

In [59]:
3.0

3.0

In [60]:
1.5 + 2

3.5

In [3]:
# The result is in scientific notation: e+90 means "times 10^90".
2.0 ** 300

2.037035976334486e+90

---

Try out some arithmetic with integers.

In [61]:
# Multiplication
3 * 4

12

In [62]:
# Exponentiation
3 ** 4

81

---

The number of digits Python will keep a record of is basically limited by the computer's memory.

In [63]:
123456789 ** 123

180443894485522835714954192172999280028845717532682776236340940102536698145222569108484463188835141501257568786614496374890490631237110580592001682129147574651845715171456148359301092015447205623057495772659564027213301182232076238590331900681806078027178740976490955033321310868454820309128358774485790967770683032944024352558539124788679067434454263656340662912379366253271751953736731074819372491000795297394853010105837025484346139393089929535058486260828830048634323191537485125711757553017086494262086507174576160642886415424336562785001644174485982226421972489721110767356064962137106505728778418700556641023076586539800506459911177905554903899443902042199874341653922049139720885160820424705059531702449496414152206583904252440335125073512355264351679192059781951740756716496372272101373104569806788535169770019927578333904122000732663242308371786294445444694565563343590247938552086658203292972070407426713686306344322058332865613102498986620473134625473086906778038872631750464721441869

---

Integer arithmetic with division leads to float values.

In [64]:
# Division with positive remainder
7 / 3

2.3333333333333335

In [65]:
# Division with no remainder
8/4

2.0

---

In [66]:
1 + 2 * 3 * 4 * 5 / 6 ** 3 + 7 + 8 - 9 + 10

17.555555555555557

General arithmetic that include float values lead to float values.

In [67]:
1.5 + 2

3.5

In [68]:
2 ** 0.5

1.4142135623730951

In [69]:
(2 ** 0.5) * (2 ** 0.5)

2.0000000000000004

---

Float values tend to produce surprising results.

In [70]:
# floating-point rounding
0.12345678901234567890123456789

0.12345678901234568

In [71]:
0.12345678901234567890123456789 - 0.1234567890123456789

0.0

---

Scientific notation is used.

In [72]:
# For readability, you can use _
6 / 4_000

0.0015

In [73]:
6 / 400_000_000

1.5e-08

In [74]:
1.5e-08

1.5e-08

---

Be careful of your syntax. Sometimes common notation from mathematics or other languages do not work here.

In [75]:
x = 5

In [76]:
2 * x

10

In [77]:
# A SyntaxError
# 2x

---

## Strings

---

### Text and Strings

* A string (`str`) value is a snippet of text of any length
    * `'a'`
    * `'word'`
    * `"there can be 2 sentences. Here's the second!"`
* Strings consisting of numbers can be converted to numbers
    * `int('12')`
    * `float('1.2')`
* Any value can be converted to a string
    * `str(5)`

---

### Demo: Strings

Explore how quotation marks are used to make strings.

In [78]:
"data" + "science"

'datascience'

In [79]:
"data" + " " + "science"

'data science'

In [80]:
# A SyntaxError:
# 'Don't always use single quotes'

"Flavor"
x = len ("Flavor")
x

Notice that there is some kind of "arithmetic" with strings.

In [81]:
# concatenation
'straw' + 'berry' # concatenation

'strawberry'

In [82]:
"That's " + str(1 + 1) + ' ' + str(True)

"That's 2 True"

In [83]:
x = 'straw'
y = 'berry'
x + y

'strawberry'

In [84]:
'ha' * 100

'hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha'

In [85]:
'ha' + str(10)

'ha10'

In [86]:
# A TypeError
# 'lo' * 5.5

In [87]:
int('3')

3

In [88]:
"This won't work with a single-quoted string!"

"This won't work with a single-quoted string!"

---

## Boolean Values

---

### `bool`

* Boolean values are used to represent truth or falsehood
* They can only have two possible values:
    * `True`
    * `False`
* This data type can be used to control the flow of code and aid in data analysis.

In [ ]:
2 == 2

In [ ]:
1 == 0

In [ ]:
(3 * 4) / 6 < 1 + 2 + 3 + 4

In [21]:
round == round

True

---

## Type Casting

---

### Type Casting

* Type casting is the process of converting a value from one data type to another
* Strings that contain numbers can be converted to floats and sometimes integers
    * `int('12')`
    * `float('1.2')`
    * `float('one point two')` --- **Not a Good Idea!**
* Any value can be converted to a string
    * `str(5)`
* Numbers can be converted to other numeric types
    * `float(1)`
    * `int(1.2)` --- **DANGER: Loses Information!**

---

### Demo: Type Casting

Try converting between strings and other data types.

In [89]:
int('12')

12

In [90]:
'ha' + str(10)

'ha10'

In [91]:
# A ValueError
int('3.0')

ValueError: invalid literal for int() with base 10: '3.0'

In [2]:
str(5)

'5'

In [3]:
float(1)

1.0

In [4]:
int(1.2)

1

---

## No Value

---

### `NoneType`

* Somethings in Python have a `NoneType` data type.
* `None` is an example of something in Python without value.

### Demo: `NoneType`

In [5]:
None

In [6]:
print("Hello")

Hello

---

## Attributes and Methods

---

### Attributes and Methods

* Python is an Object Orientated Programming language
* Almost everything in Python is an object
* Objects usually have attributes and methods associated with them
    * An attribute is some characteristic of the object
    * A method is some function associated with the object
* Using a `.` after an object will allow you to access the object's attributes and methods
* In Jupyter, press the tab key after the `.` to see a list of available attributes and methods

### String methods
* Associated with strings are special functions, called **string methods**.
* Access string methods with a `.` after the string ("dot notation").    
    * For instance, to use the `upper` method on string `s`, we write `s.upper()`.
* Examples include `upper`, `title`, and `replace`, but there are [many more](https://docs.python.org/3/library/stdtypes.html#string-methods).

---

### Demo: Attributes and Methods

Replace a character in a string with another character.

In [7]:
'hitchhiker'.replace('hi', 'ma')

'matchmaker'

In [8]:
"Flavor"
x = len ("Flavor")
x

6

In [ ]:
# a_string was not updated
a_string

In [ ]:
?str.islower

In [ ]:
"loud".upper()

In [ ]:
s = "train"
t = s.replace('t', 'ing')
u = t.replace('in', 'de')
u

In [7]:
fave_string = 'My favorite class is CS 8A!'

In [8]:
fave_string.title()

'My Favorite Class Is Cs 8A!'

In [9]:
fave_string.upper()

'MY FAVORITE CLASS IS CS 8A!'

In [10]:
fave_string.replace('favorite', '😍' * 3)

'My 😍😍😍 class is CS 8A!'

---

In [11]:
# len is not a method, since it doesn't use dot notation.
len(fave_string)

27

### Concept Check ✅ 

Assume you have run the following statements:

```py
x = 3
y = '4'
z = '5.6'
```

Choose the expression that will be evaluated **without** an error.

A. `x + y`

B. `x + int(y + z)`

C. `str(x) + int(y)`

D. `str(x) + z`

E. All of them have errors

## Sequences

---

## Overview

* [Sequences](#Sequences)
* [Beyond the Python Library](#Beyond-the-Python-Library)
* [Arrays](#Arrays)
* [Indexing Sequences](#Indexing-Sequences)
* [NumPy](#NumPy)

---

## Sequences

A sequenced data type represents an ordered collection

<img src="./sequence_blocks.png"  alt="A sequence visualized a collection of blocks" width = 40%>

---

### Built-In Sequence Data Types

There are several built-in sequence data types in Python such as:
*  Strings (`str`):
    * A text sequence of characters
    * `"data science"`
*  Lists (`list`):
    * A sequence of a mixture of data types
    *  `['a', 1, max]`
*  Ranges (`range`):
    * A sequence of numbers
    * `range(10)`

---

### Demo: Built-In Sequence Types

Create a string and notice the length of a string includes the blank space.

In [95]:
a_string = "data science"
a_string

'data science'

---

Create a list, notice it contains a mixture of data types, and check it's length

In [ ]:
a_list = ['a', 1, max]
a_list

In [14]:
first_four = [1, 2, 3, 4]

In [15]:
type(first_four)

list

In [ ]:
first_four * 2

In [ ]:
str_array = ['ha', 'he', 'ho']

In [ ]:
str_array

---

### Ranges
* A **range** is an array of evenly spaced numbers. We create ranges using `np.arange`.
* The most general way to create a range is `np.arange(start, end, step)`. This returns an array such that:
    - The first number is `start`. **By default, `start` is 0.**
    - All subsequent numbers are spaced out by `step`, until (but excluding) `end`. **By default, `step` is 1.**

In [18]:
# Start at 0, end before 8, step by 1.
# This will be our most common use-case!
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
# Start at 5, end before 10, step by 1.
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [20]:
# Start at 3, end before 32, step by 5.
np.arange(3, 32, 5)

array([ 3,  8, 13, 18, 23, 28])

---

Convert the range to a list to see the items.

In [ ]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

---

## Beyond the Python Library

### Modules, Libraries, and Packages

* Modules, libraries, and packages are collections of Python code
    * Python has a built-in module called `math` that contains a collection of mathematical functions and values 
    * `datascience` is a package written by staff at UC Berkeley for this course
    * `Matplotlib` is a standard data visualization library
* The `import` command is a way to load modules, libraries, and packages into the coding environment
    * `from datascience import *` imports everything from the `datascience` package
    * `import numpy as np` imports the NumPy package and provides it with the common shorter name (alias) `np`

In [14]:
# The math module is extremely useful in computing mathematical expressions in Python.
import math
math.e

2.718281828459045

In [15]:
math.pi

3.141592653589793

In [ ]:
radius = 5
area_of_circle = radius**2 * math.pi
area_of_circle

In [ ]:
math.sqrt(5)

In [ ]:
# Calculating logarithms (the logarithm of 8 in base 2).
# The result is 3 because 2 to the power of 3 is 8.
math.log(8, 2)

---

## Arrays

---

### Arrays

* An array (`numpy.ndarray`) is a sequenced type from the `NumPy` package
* All elements in an array have the same data type
* Math operations work on each element of the array separately
* When adding arrays, elements are added one by one (if they have the same length)
* They're better than lists for handling big datasets efficiently
* You can make an array with the `make_array` function from the `datascience` package

---

### Demo: Arrays

Create an array using `make_array`.

In [ ]:
first_four = make_array(1, 2, 3, 4)

In [ ]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

---

Explore using array arithmetic and notice that the operations create a new array.

In [ ]:
next_four = make_array(5, 6, 7, 8)

In [ ]:
first_four + next_four

In [ ]:
only_three = make_array(5, 6, 7)

---

Use some functions such as `len` and `sum` on an array

In [ ]:
next_four.item(0)

In [ ]:
len(next_four)

In [ ]:
np.average(next_four)

In [ ]:
# Built-in sum
np.sum(next_four)

In [ ]:
# NumPy sum - optimized for arrays
import numpy as np

---

There are some rules for array arithmetic. For example, you can only add arrays of the same length.

In [ ]:
my_array = make_array(1, 2, 3, 4)

In [ ]:
another = make_array(5, 6, 7, 8)

In [ ]:
another

In [ ]:
yet_another = make_array(9, 11, 4)

In [ ]:
# A ValueError
# my_array + yet_another

---

You can make an array with non-numeric data types.

In [ ]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

---

## Indexing Sequences

---

### Indexes

<img src="./sequence_blocks_with_indices.png"  alt="A sequence visualized a collection of blocks with the index values included" width = 45%>

Sequence data types have a variety of ways to access each item in the sequence:
* A standard way: Use the item's position number in the sequence (index) with bracket `[...]` notation
    * Indices start with `0`

---

### Demo: Indexing

Get the first character from a string.

In [ ]:
another_string = "Foothill College"
another_string

In [ ]:

first_char = another_string[0]
print(first_char)

---

Get the last character from a string.

In [ ]:
.# Assign a string to a variable
data8_string = "UC Berkeley Data 8"

# Access the last character using the index -1
last_character = data8_string[-1]

# Print the result
print(last_character)

In [ ]:
# An IndexError
# another_string[13]

In [ ]:
# Another way to access the last item in a sequence.
another_string[-1]

---

Access items in an array using .item and bracket notation.

In [ ]:
an_array = make_array('eats', 'shoots', 'leaves')
an_array

In [ ]:
an_array.item(0)

In [ ]:
an_array.item(1)

In [ ]:
an_array.item(2)

---

Be careful! Check your data types because sometimes you don't get what you expect.

In [ ]:
another_array = make_array(10, 20, 30)
another_array

---

### NumPy


<img src='numpy.png' width=300>


- NumPy (pronounced "num pie") is a Python library (module) that provides support for **arrays** and operations on them.

- To use `numpy`, we need to import it. It's usually imported as `np`

* NumPy is a Python library with a collection of tools optimized to work with arrays
* In our reference material, array tools commonly start with `np`
* One function `np.arange` is really helpful for generating arrays of numbers
    * General command: `np.arange(start, stop, step)`
    * the `start` and `step` values have a default of 0 and 1, respectively
    * `np.arange(5)` creates the array `array([0, 1, 2, 3, 4])`
    * `np.arange(1, 5)` creates the array `array([1, 2, 3, 4])`
    * `np.arange(1, 5, 2)` creates the array `array([1, 3])`
    * `np.arange` is not the same as `range`

---

### Demo: NumPy Functions

Generate arrays with `arange`.

In [ ]:
my_array = np.arange(5)

2.718281828459045

In [ ]:
my_array = np.arange(1,5)

In [ ]:
my_array = np.arange(1, 5, 2)
my_array

---

Demonstrate a few NumPy functions, attributes, and methods.

In [ ]:
range_arr = np.arange(0, 10, 2) # start, stop (exclusive), step

In [ ]:
sqrt_arr = np.sqrt([4, 9, 16])

In [ ]:
unsorted_arr = np.array([3, 1, 2])
sorted_arr = np.sort(unsorted_arr)

---

# Tables

---

* [Tables](#Tables)
* [Attributes and Properties](#Attributes-and-Properties)
* [Some Table Methods](#Some-Table-Methods)

---

## Tables

---

### Table Structure

* The `datascience` library contains a data type called a `Table`.
* A `Table` is a sequence of labeled columns
* Each row represents one individual
* Data within a column represents one attribute of the individuals

<img src="./table_structure.png" alt="A table with the columns and rows indicated." width=50%>

---

### Loading Data

* Data analysis usually includes connecting to various data sources
* We focus on loading data from CSV files
    * Comma Separated Values
    * `.csv` extension
* The `Table.read_table` function will load the contents of a CSV into the notebook as a `Table`.

---

### Demo: Loading Data

In [16]:
states = Table.read_table('states_area.csv')
states

State      | Total Area (sq mi) | Land Area (sq mi) | Water Area (sq mi)
Alaska     | 665384             | 570641            | 94743.1
Texas      | 268596             | 261232            | 7364.75
California | 163695             | 155779            | 7915.52
Montana    | 147040             | 145546            | 1493.91
New Mexico | 121590             | 121298            | 292.15
Arizona    | 113990             | 113594            | 396.22
Nevada     | 110572             | 109781            | 790.65
Colorado   | 104094             | 103642            | 451.78
Oregon     | 98378.5            | 95988             | 2390.53
Wyoming    | 97813              | 97093.1           | 719.87
... (40 rows omitted)

In [17]:
states.show(5)

In [97]:
type(states)

datascience.tables.Table

---

## Attributes and Properties

A `Table` has information that we can access by command. For example:
* `t.labels` - the labels of a table called `t`
* `t.num_columns` - the number of columns in `t`
* `t.num_rows` - the number of rows in `t`
* `t.rows` - a collection of all the rows in `t`

---

### Demo: Attributes and Properties

There are various attributes of a table that you can access as well using the dot notation such as `labels`, `num_columns`, and `num_rows`.

In [98]:
states.labels

('State', 'Total Area (sq mi)', 'Land Area (sq mi)', 'Water Area (sq mi)')

In [99]:
states.num_columns

4

In [100]:
states.num_rows

50

In [101]:
states.rows

Rows(State      | Total Area (sq mi) | Land Area (sq mi) | Water Area (sq mi)
Alaska     | 665384             | 570641            | 94743.1
Texas      | 268596             | 261232            | 7364.75
California | 163695             | 155779            | 7915.52
Montana    | 147040             | 145546            | 1493.91
New Mexico | 121590             | 121298            | 292.15
Arizona    | 113990             | 113594            | 396.22
Nevada     | 110572             | 109781            | 790.65
Colorado   | 104094             | 103642            | 451.78
Oregon     | 98378.5            | 95988             | 2390.53
Wyoming    | 97813              | 97093.1           | 719.87
... (40 rows omitted))

---

## Some Table Methods

There is a collection of methods (functions) associated with every `Table` created. For example:
* `t.show(n)` - displays the first `n` rows of a table called `t`
* `t.select(label)` - constructs a new table with just the specified columns
* `t.drop(label)` - constructs a new table in which the specified columns are omitted
* `t.sort(label)` - constructs a new table with rows sorted by the specified column
* `t.where(label, condition)` - constructs a new table with just the rows that match the condition
    * Initially, the `condition` will be made up using Predicates such as `are.above`, `are.equal_to`, etc. 
* More can be found in the [`datascience` documentation](https://datascience.readthedocs.io/en/master/tables.html)

---

### Demo: `show`

Explore the `show` table method.

In [102]:
states.show(3)

In [103]:
# show(3) does not produce a Table
states_show_3 = states.show(3)
type(states_show_3)

NoneType

---

### Demo: `select`

Use the `select` table method to select columns by column labels and column indexes.

In [104]:
states.select('State')

State
Alaska
Texas
California
Montana
New Mexico
Arizona
Nevada
Colorado
Oregon
Wyoming
... (40 rows omitted)

In [105]:
states.select('Water Area (sq mi)')

Water Area (sq mi)
94743.1
7364.75
7915.52
1493.91
292.15
396.22
790.65
451.78
2390.53
719.87
... (40 rows omitted)

In [106]:
# A NameError where the column name was used incorrectly.
states.select(State, 'Total Area (sq mi)')

NameError: name 'State' is not defined

In [107]:
# A ValueError where the column name was used incorrectly.
states.select('State', 'Total Area')

ValueError: The column "Total Area" is not in the table. The table contains these columns: State, Total Area (sq mi), Land Area (sq mi), Water Area (sq mi)

---

### Demo: `drop`

Use the `drop` table method to drop columns by name and by index.

In [ ]:
states.drop('Total Area (sq mi)')

In [ ]:
states

---

### Demo: `sort`

Use the `sort` table method to sort the data in the table by a certain column.

In [ ]:
states.sort('State')

In [ ]:
states.sort(1)

---

### Demo: `where`

Use the `where` table method to filter the data in the table.

|Predicate|Example|Result|
|-|-|-|
|`are.equal_to`|`are.equal_to(50)`|Find rows with values equal to 50|
|`are.not_equal_to`|`are.not_equal_to(50)`|Find rows with values not equal to 50|
|`are.above`|`are.above(50)`|Find rows with values above (and not equal to) 50|
|`are.above_or_equal_to`|`are.above_or_equal_to(50)`|Find rows with values above 50 or equal to 50|
|`are.below`|`are.below(50)`|Find rows with values below 50|
|`are.between`|`are.between(2, 10)`|Find rows with values above or equal to 2 and below 10|
|`are.between_or_equal_to`|`are.between_or_equal_to(2, 10)`|Find rows with values above or equal to 2 and below or equal to 10|

In [108]:
# Nothing Filtered
states

State      | Total Area (sq mi) | Land Area (sq mi) | Water Area (sq mi)
Alaska     | 665384             | 570641            | 94743.1
Texas      | 268596             | 261232            | 7364.75
California | 163695             | 155779            | 7915.52
Montana    | 147040             | 145546            | 1493.91
New Mexico | 121590             | 121298            | 292.15
Arizona    | 113990             | 113594            | 396.22
Nevada     | 110572             | 109781            | 790.65
Colorado   | 104094             | 103642            | 451.78
Oregon     | 98378.5            | 95988             | 2390.53
Wyoming    | 97813              | 97093.1           | 719.87
... (40 rows omitted)

In [18]:
California = states.where('State', 'California')
California.show(5)

In [19]:
California = states.where('State', are.equal_to("California"))
California

State      | Total Area (sq mi) | Land Area (sq mi) | Water Area (sq mi)
California | 163695             | 155779            | 7915.52

In [111]:
California = states.where('Land Area (sq mi)', are.above(10000))
California

State      | Total Area (sq mi) | Land Area (sq mi) | Water Area (sq mi)
Alaska     | 665384             | 570641            | 94743.1
Texas      | 268596             | 261232            | 7364.75
California | 163695             | 155779            | 7915.52
Montana    | 147040             | 145546            | 1493.91
New Mexico | 121590             | 121298            | 292.15
Arizona    | 113990             | 113594            | 396.22
Nevada     | 110572             | 109781            | 790.65
Colorado   | 104094             | 103642            | 451.78
Oregon     | 98378.5            | 95988             | 2390.53
Wyoming    | 97813              | 97093.1           | 719.87
... (31 rows omitted)

---

### Summary

- Assignment statements allow us to bind values to variables.
- We can call functions in Python similar to how we call functions in math.
    - Python knows some functions by default. Import statements allow us to bring in additional functions.
- All values in Python have a data type.
    - `int`s and `float`s are numbers. Strings (`str`) are for text.
    - `int`s are integers, while `float`s contain decimal points.
    - Strings should be enclosed in single or double quotes.

Lists and arrays are used to store **sequences**.
    - Arrays are faster and more convenient for numerical operations.
    - Arrays make it easy to perform arithmetic operations on all elements of an array and to perform element-wise operations on multiple arrays.
     - Access elements by position, starting at position 0.
- Ranges are arrays of equally-spaced numbers. We create ranges with the function `np.arange`.


For your reference, here's a table of all the functions and methods. We'll learn more methods to add to this table in the coming week!

|Name|Example|Purpose|
|-|-|-|
|`sort`|`tbl.sort("N")`|Create a copy of a table sorted by the values in a column|
|`where`|`tbl.where("N", are.above(2))`|Create a copy of a table with only the rows that match some *predicate*|
|`num_rows`|`tbl.num_rows`|Compute the number of rows in a table|
|`num_columns`|`tbl.num_columns`|Compute the number of columns in a table|
|`select`|`tbl.select("N")`|Create a copy of a table with only some of the columns|
|`drop`|`tbl.drop("N")`|Create a copy of a table without some of the columns|

## Attribution

This content is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)</a> and derived from the <a href="https://www.data8.org/">Data 8: The Foundations of Data Science</a> offered by the University of California, Berkeley.

<img src="./by-nc-sa.png" width=100px>